---
- name: (RedHat) pkg install
  when: ansible_os_family == 'RedHat'
  include: install_RedHat.yml

- name: (Debian) pkg install
  when: ansible_os_family == 'Debian'
  include: install_Debian.yml

- name: configure...
  template: src=etc/ntp.conf.j2 dest=/etc/ntp.conf mode=644 owner=root group=root

- name: Restart ntp(d)
  service: name=ntp state=restarted enabled=yes